from __future__ import annotations

import pytest

import cangjie_images.prepare as prepare
from cangjie_images.prepare import (
    _BUILD_CONTEXT_MARKER,
    _build_smoke_test_env,
    _prepare_output_dir,
    EnvDiff,
    PathListDiff,
    _should_exclude,
    _split_path_diff,
    render_dockerfile,
    rewrite_paths,
)


def test_should_exclude_windows_runtime() -> None:
    assert _should_exclude("cangjie/runtime/lib/windows_x86_64_cjnative/libfoo.so")
    assert _should_exclude("cangjie/lib/windows_x86_64_cjnative/libbar.a")
    assert _should_exclude("cangjie/modules/windows_x86_64_cjnative/core.cjo")
    assert _should_exclude("cangjie/third_party/mingw/bin/gcc")
    assert _should_exclude("cangjie/third_party/mingw")


def test_should_exclude_top_level_dlls() -> None:
    assert _should_exclude("cangjie/lib/libstdFFI.dll")
    assert _should_exclude("cangjie/lib/libstdFFI.dll.a")


def test_should_keep_linux_artifacts() -> None:
    assert not _should_exclude("cangjie/bin/cjc")
    assert not _should_exclude("cangjie/lib/libstdFFI.so")
    assert not _should_exclude("cangjie/lib/linux_x86_64_cjnative/libboundscheck.so")
    assert not _should_exclude("cangjie/runtime/lib/linux_aarch64_cjnative/libcangjie-runtime.a")
    assert not _should_exclude("cangjie/third_party/llvm/bin/clang")
    assert not _should_exclude("cangjie/envsetup.sh")


def test_split_path_diff_finds_baseline_in_middle() -> None:
    before = "/usr/bin:/bin"
    after = "/opt/cangjie/bin:/opt/cangjie/tools/bin:/usr/bin:/bin:/root/.cjpm/bin"
    diff = _split_path_diff(before, after)
    assert diff.prepend == ("/opt/cangjie/bin", "/opt/cangjie/tools/bin")
    assert diff.append == ("/root/.cjpm/bin",)


def test_split_path_diff_baseline_only_prepended() -> None:
    diff = _split_path_diff("/usr/bin", "/opt/cj/bin:/usr/bin")
    assert diff.prepend == ("/opt/cj/bin",)
    assert diff.append == ()


def test_split_path_diff_empty_baseline_treats_all_as_prepend() -> None:
    diff = _split_path_diff("", "/opt/cj/runtime/lib:/opt/cj/tools/lib")
    assert diff.prepend == ("/opt/cj/runtime/lib", "/opt/cj/tools/lib")
    assert diff.append == ()


def test_split_path_diff_trailing_colon_is_stripped() -> None:
    # envsetup.sh on 1.0.5 emits LD_LIBRARY_PATH=...:$LD_LIBRARY_PATH where
    # the trailing expansion is empty, leaving a dangling colon.
    diff = _split_path_diff("", "/opt/cj/lib:")
    assert diff.prepend == ("/opt/cj/lib",)
    assert diff.append == ()


def test_split_path_diff_dedupes_prepend_entries() -> None:
    # If envsetup ends up emitting duplicate entries (e.g. double-source),
    # dedupe so the rendered ENV line stays tight.
    before = "/usr/bin"
    after = "/opt/cj/bin:/opt/cj/bin:/usr/bin"
    diff = _split_path_diff(before, after)
    assert diff.prepend == ("/opt/cj/bin",)


def test_split_path_diff_falls_back_when_baseline_not_contiguous() -> None:
    before = "/a:/b"
    after = "/a:/c"  # /b dropped, /c added — no contiguous match
    diff = _split_path_diff(before, after)
    assert diff.prepend == ("/c",)
    assert diff.append == ()


def test_rewrite_paths_replaces_host_prefix() -> None:
    env = EnvDiff(
        assignments={"CANGJIE_HOME": "/tmp/stage/opt/cangjie"},
        path_diffs={
            "PATH": PathListDiff(
                prepend=("/tmp/stage/opt/cangjie/bin", "/tmp/stage/opt/cangjie/tools/bin"),
                append=("/root/.cjpm/bin",),
            ),
            "LD_LIBRARY_PATH": PathListDiff(
                prepend=("/tmp/stage/opt/cangjie/runtime/lib/linux_x86_64_cjnative",),
                append=(),
            ),
        },
    )
    result = rewrite_paths(env, "/tmp/stage/opt/cangjie", "/opt/cangjie")
    assert result.assignments["CANGJIE_HOME"] == "/opt/cangjie"
    assert result.path_diffs["PATH"].prepend == ("/opt/cangjie/bin", "/opt/cangjie/tools/bin")
    assert result.path_diffs["PATH"].append == ("/root/.cjpm/bin",)
    assert result.path_diffs["LD_LIBRARY_PATH"].prepend == (
        "/opt/cangjie/runtime/lib/linux_x86_64_cjnative",
    )


def test_prepare_output_dir_rejects_existing_non_generated_dir(tmp_path) -> None:
    output_dir = tmp_path / "context"
    output_dir.mkdir()
    keep = output_dir / "keep.txt"
    keep.write_text("do not delete", encoding="utf-8")

    with pytest.raises(FileExistsError):
        _prepare_output_dir(output_dir)

    assert keep.read_text(encoding="utf-8") == "do not delete"


def test_prepare_output_dir_reuses_prior_generated_dir(tmp_path) -> None:
    output_dir = tmp_path / "context"
    output_dir.mkdir()
    (output_dir / _BUILD_CONTEXT_MARKER).write_text("generated by cangjie-images\n", encoding="utf-8")
    stale = output_dir / "stale.txt"
    stale.write_text("old", encoding="utf-8")

    _prepare_output_dir(output_dir)

    assert output_dir.is_dir()
    assert not stale.exists()
    assert (output_dir / _BUILD_CONTEXT_MARKER).is_file()


def test_build_smoke_test_env_uses_clean_baseline(monkeypatch, tmp_path) -> None:
    monkeypatch.setenv("PATH", "/host/tools:/usr/bin")
    monkeypatch.setenv("LD_LIBRARY_PATH", "/host/lib")
    monkeypatch.setenv("HOME", "/host/home")

    env = _build_smoke_test_env(
        tmp_path / "sdk-root" / "opt" / "cangjie",
        EnvDiff(
            assignments={"LD_LIBRARY_PATH": "/opt/cangjie/runtime/lib", "FOO": "bar"},
            path_diffs={
                "PATH": PathListDiff(
                    prepend=("/opt/cangjie/bin", "/opt/cangjie/tools/bin"),
                    append=("/root/.cjpm/bin",),
                )
            },
        ),
    )

    assert env["PATH"] == (
        "/opt/cangjie/bin:/opt/cangjie/tools/bin:"
        f"{prepare._BASELINE_PATH}:/root/.cjpm/bin"
    )
    assert env["LD_LIBRARY_PATH"] == "/opt/cangjie/runtime/lib"
    assert env["HOME"] == prepare._BASELINE_HOME
    assert env["FOO"] == "bar"
    assert "/host/tools" not in env["PATH"]
    assert env["LD_LIBRARY_PATH"] != "/host/lib"


def test_render_dockerfile_path_uses_env_expansion() -> None:
    diff = EnvDiff(
        assignments={"CANGJIE_HOME": "/opt/cangjie"},
        path_diffs={
            "PATH": PathListDiff(
                prepend=("/opt/cangjie/bin", "/opt/cangjie/tools/bin"),
                append=("/root/.cjpm/bin",),
            ),
            "LD_LIBRARY_PATH": PathListDiff(
                prepend=("/opt/cangjie/runtime/lib/linux_x86_64_cjnative",),
                append=(),
            ),
        },
    )
    content = render_dockerfile(
        base_image="debian:bookworm-slim",
        base_family="debian",
        channel="lts",
        version="1.0.5",
        env_diff=diff,
        sdk_context_dir="sdk-root",
    )
    assert 'ENV CANGJIE_HOME="/opt/cangjie"' in content
    assert 'ENV PATH="/opt/cangjie/bin:/opt/cangjie/tools/bin:$PATH:/root/.cjpm/bin"' in content
    assert 'ENV LD_LIBRARY_PATH="/opt/cangjie/runtime/lib/linux_x86_64_cjnative:$LD_LIBRARY_PATH"' in content


def test_render_dockerfile_scalar_env_escapes_dollar() -> None:
    diff = EnvDiff(
        assignments={"X": 'a"b$c\\d'},
        path_diffs={},
    )
    content = render_dockerfile(
        base_image="x",
        base_family="debian",
        channel="c",
        version="v",
        env_diff=diff,
        sdk_context_dir="sdk-root",
    )
    # Scalars escape $ so values are treated as literal strings.
    assert 'ENV X="a\\"b\\$c\\\\d"' in content
